name: the-big-voice
dependencies:
  - python=3.12
  - pip
  - pip:
    - numpy
    - flask
    - flask_cors
    - werkzeug
    - pandas
    - librosa
    - pydub
    - scipy
    - matplotlib
    - umap-learn
